[package]
name = "ribbon_chumsky"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = { version = "0.12.0", features = ["pratt"] }
logos = "0.16.0"
string-interner = "0.19.0"
